config/routes.rb
CousinsWebsite::Application.routes.draw do

  root 'programs#index'

  get '/search' => 'programs#search'
  post '/search' => 'programs#search'

  get '/submit' => 'programs#submit'
  get '/admin_submit' => 'programs#admin_submit'

  get '/admin' => 'pages#admin'

  resources :programs

  post '/programs/:id/toggle_published' => 'programs#toggle_published', defaults: { format: :json }

  resources :answers

  resources :questions

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  has_many :program_questions
  has_many :programs, :through => :program_questions
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
    render layout: 'admin'
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    render layout: 'admin'
  end

  # GET /questions/new
  def new
    @question = Question.new
    render layout: 'admin'
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to '/questions', notice: 'Question was successfully created.' }
        format.json { render action: 'questions#index', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to '/questions', notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to '/questions' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<div class="container-fluid" style="margin-top: 50px;">
  <ul>
    <% @questions.each do |question| %>
      <li>
        <%= question.question %>
        <%= link_to 'Show', question %>
        <%= link_to 'Edit', edit_question_path(question) %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %>
        <ul>
          <% question.answers.each do |answer| %>
            <li>
              <%= answer.answer %>
              <%= link_to 'Show', answer %>
              <%= link_to 'Edit', edit_answer_path(answer, question_id: question.id.to_s) %>
              <%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %>
            </li>
          <% end %>
          <li>
            <%= link_to 'Add Answer', new_answer_path(question_id: question.id.to_s) %>
          </li>
        </ul>
      </li>
    <% end %>
    <li>
      <%= link_to 'Add Question', new_question_path %>
    </li>
  </ul>
</div>

app/views/questions/new.html.erb
<div class="container-fluid" style="margin-top: 50px;">
  <%= render 'form' %>

  <%= link_to 'Back', questions_path %>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>