config/routes.rb
CousinsWebsite::Application.routes.draw do

  root 'programs#index'

  get '/search' => 'programs#search'
  post '/search' => 'programs#search'

  get '/submit' => 'programs#submit'
  get '/admin_submit' => 'programs#admin_submit'

  get '/admin' => 'pages#admin'

  resources :programs

  post '/programs/:id/toggle_published' => 'programs#toggle_published', defaults: { format: :json }

  resources :answers

  resources :questions

  

end

app/models/program.rb
class Program < ActiveRecord::Base
  has_many :program_answers
  has_many :program_questions
  has_many :answers, :through => :program_answers
  has_many :questions, :through => :program_questions
  after_initialize :init

  def init
    self.published = false if self.published.nil?
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :authenticate, except: [:index, :create, :search, :submit]
  before_action :set_program, only: [:show, :edit, :update, :destroy, :toggle_published]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.where(published: true)
  end

  def search
    @answer_ids = []
    @question_ids = []
    if params.include? 'question'
      params['question'].each_pair do |q_id, a_ids|
        @question_ids << q_id.to_i
        @answer_ids += a_ids.reject &:empty?
      end
    end
    @answer_ids.map! &:to_i

    @programs = []
    Program.where(published: true).each do |program|
      search_matches = true
      Question.all.each do |question|
        if @question_ids.include? question.id and program.question_ids.include? question.id
          Answer.all.each do |answer|
            if @answer_ids.include? answer.id and not program.answer_ids.include? answer.id
              search_matches = false
            end
          end
        end
      end
      if search_matches
        @programs << program
      end
    end

    respond_to do |format|
      format.html { render partial: 'results', status: :ok, layout: false }
      format.js { render 'results' }
    end
  end

  def toggle_published
    @program.published = !@program.published
    respond_to do |format|
      if @program.save
        format.json { render json: { publish_button_text: view_context.publish_button_text(@program) }, status: :ok, layout: false }
      end
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    render layout: 'admin'
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  def submit
    new
  end

  def admin_submit
    @admin = true
    new
    render layout: 'admin'
  end
  # GET /programs/1/edit
  def edit
    render layout: 'admin'
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    answer_ids = []
    question_ids = []
    if params.include? 'question'
      params['question'].each_pair do |q_id, a_ids|
        question_ids << q_id.to_i
        answer_ids += a_ids.reject &:empty?
      end
      answer_ids.map! &:to_i
      question_ids.map! &:to_i
    end
    @program.questions = Question.find(question_ids)
    @program.answers = Answer.find(answer_ids)

    respond_to do |format|
      if @program.save
        format.html { redirect_to root_path, notice: 'Program was successfully created.' }
        format.json { render action: 'pages#home', status: :created, location: @program }
      else
        format.html { render action: 'new' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to '/admin' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :desc, :website, :contact_name, :contact_phone, :contact_email)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
  def publish_button_text program
    if program.published
      'Published'
    else
      'Not Published'
    end
  end
end

app/views/programs/_form.html.erb
<div class="container wrapper"> 
    <!-- Instructions for admin side-->
    <div class="col-md-12" style="margin-bottom:10px;color: #666;font-size: 1.1em;border: 1px solid #fff;border-radius: 8px;background-color:white;">
        <div class="col-md-4">
            <ul class="" style="margin: 20px 0;">
                <li>Please be specific in regards to your programs. Do not simply select all options to cast a wide net.</li>

            </ul>
        </div>
        <div class="col-md-4">
            <ul class="" style="margin: 20px 0;">
                <li>We will not publish organization names, but rather the name of the PROGRAM
                    that the organization offers. E.g. TME Summer Institute not just UNB or TME.</li>
            </ul>
        </div>
        <div class="col-md-4">
            <ul class="" style="margin: 20px 0;">
                <li>Once you submit your listing CHANGES CANNOT BE MADE, the post must be deleted and re-submitted to make any changes (email <a href="mailto:info@programpointer.com?subject=Program Pointer - Request for Program Removal">info@programpointer.com</a> to request delete).</li>

            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <%= form_for(@program) do |f| %>
            <% if @program.errors.any? %>
            <div id="error_explanation">
                <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

                <ul>
                    <% @program.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
            <% end %>
            <!-- Nav tabs -->
            <!--                    <ul class="nav  nav-pills" role="tablist">
                                            <li class="active"><a style="color:  #66c666;"  id="generalinfo" href="#home" role="tab" data-toggle="tab">General Info</a></li>
                                            <li><a  style="color: #f7ae11;" href="#profile" id="questionanswer" role="tab" data-toggle="tab">Choose your answers</a></li>
                                        </ul>-->

            <!-- Tab panes -->
            <div class="tab-content" style="padding-top:5px;">
                <div class="tab-pane active" id="home">
                    <span id='title-green'>General Information</span>
                    <div class="row">
                        <div class="col-md-12 intro-text getlisted-general-info">
                            <div class="form-group">
                                <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Program Name' %>
                            </div>
                            <div class="form-group">
                                <%= f.text_field :website, class: 'form-control input-lg', placeholder: 'Website URL' %>
                            </div>
                            <div class="form-group">
                                <%= f.text_field :contact_name, class: 'form-control input-lg', placeholder: 'Contact Person' %>
                            </div>
                            <div class="form-group">
                                <%= f.text_field :contact_phone, class: 'form-control input-lg', placeholder: 'Phone Number' %>
                            </div>
                            <div class="form-group">
                                <%= f.text_field :contact_email, class: 'form-control input-lg', placeholder: 'Contact Email' %>
                            </div>
                            <div class="form-group">
                                <%= f.text_area :desc, class: 'form-control input-lg', placeholder: 'Description' %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-md-offset-8">                                                   
                            <button id="getlisted-QA" type="button" style="float: right" class="btn btn-default btn-lg btn-block">Next <%= image_tag 'rsz_next.png' %></button>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="profile">
                    <div class="panel-group" id="accordion">
                        <p id='title-orange'>Choose your matching answers</p>
                        <% Question.all.each do |question| %>
                        <div class="panel panel-default">
                            <div class="panel-heading survey-box" target="<%= "collapse" + question.id.to_s %>">
                                 <table style="width: 100%">
                                    <tr>
                                        <td >
                                            <a data-toggle="collapse" data-parent="#accordion" href="<%= "#collapse" + question.id.to_s %>">
                                               <%= question.question_get_listed %>
                                        </a>
                                    </td>
                                    <td>                                                
                                        <span class="arrow-down"></span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div id="<%= "collapse" + question.id.to_s %>" class="panel-collapse collapse">
                             <div class="panel-body home-survey">
                                <div class="col-lg-12">
                                    <% Answer.where(question_id: question.id).each do |answer| %>
                                    <div class="row" style="margin-bottom: 10px;">
                                        <div class="col-xs-10">
                                            <div class="row">
                                                <div class="btn-group btn-group-justified" data-toggle="buttons">
                                                    <label class="btn-block btn btn-lg btn-default label-choice <%= "collapse" + question.id.to_s + "OneBtn" %>" for="question_<%= question.id %>_<%= answer.id %>" data-value="<%= answer.id %>">
                                                           <input id="question_<%= question.id %>_<%= answer.id %>" type="checkbox" value="<%= answer.id %>" name="question[<%= question.id %>][]">
                                                        <%= answer.answer %>
                                                        </input>

                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-2" style="">
                                            <div class="row">
                                                <button type="button" class="btn btn-link btn-block answer-details-btn-inactive"><strong>?</strong></button>
                                                <div class="answer-details-box pull-right" style="">
                                                    <%= answer.desc %>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <% end %>
                                    <% if @admin %>
                                    <div class="row" style="margin-bottom: 10px;">
                                        <div class="col-xs-10">
                                            <div class="row">
                                                <div class="btn-group btn-group-justified" data-toggle="buttons">
                                                    <label class="btn btn-info btn-block btn-lg selectAll" target="<%= "collapse" + question.id.to_s + "OneBtn" %>" number="">
                                                           <input type="checkbox">Select All</input>
                                                    </label> 
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
                <div class="row">
                    <div class="col-md-4">                                                   
                        <button  style="margin-bottom: 10px;" type="button" id="getlisted-GI" style="float: left" class="btn btn-default btn-lg btn-block"><%= image_tag 'rsz_prev.png' %>Previous</button>

                    </div>
                    <div class="col-md-4 col-md-offset-4">
                        <%= f.submit class: "btn btn-green btn-success btn-lg btn-block" %>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>
</div>

app/views/programs/_results.html.erb
<% @programs.each do |program| %>
  <div class="panel panel-default" style="border-radius: 0px;">
    <div class="panel-heading program-box" target="<%= "collapsePrgram" + program.id.to_s %>" style="border-radius: 0px;">
      <div class="row">
        <div class="col-md-12 item-info">
          <span class="item-title"><%= program.name %></span>
          <div class="row" style="margin-top:4px;">
            <div class="col-md-6">
              <a class="btn-link" href="<%= program.website %>" target="_blank">                                            
                <%= image_tag 'rsz_website.png' %>
                <%= program.website %>
              </a>
            </div>
            <div class="col-md-6">
              <span class="item-details">
                <%= image_tag 'rsz_contact.png' %>
                <%= program.contact_name %>
              </span>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <span class="item-details">
                <%= image_tag 'rsz_phone.png' %>
                <%= program.contact_phone %>
              </span>
            </div>
            <div class="col-md-6">
              <a class="btn-link" href="mailto:<%= program.contact_email %>">
                <%= image_tag 'rsz_email.png' %>
                <%= program.contact_email %>
              </a>
            </div>
          </div>
        </div>
        <a class="btn btn-orange" data-toggle="collapse" 
          data-parent="#accordion2" style="display:none"
          href="<%= "#collapsePrgram" + program.id.to_s %>"></a>
      </div>
    </div>
    <div id="<%= "collapsePrgram" + program.id.to_s %>" class="panel-collapse collapse">
      <div class="panel-body">
        <%= program.desc %>
      </div>
    </div>
  </div>
<% end %>

app/views/programs/_search.html.erb
<div id="side-survey">
    <%= form_tag '/search', :method => :get, remote: true do %>
    <div class="panel-group" id="accordion3">
        <% Question.all.order(:id).each do |question| %>
        <div class="panel panel-default">
            <div class="panel-heading survey-box" target="<%= "collapse" + question.id.to_s %>">
                 <table style="width: 100%">
                    <tr>
                        <td >                                                           
                            <a data-toggle="collapse" data-parent="#accordion3" href="<%= "#collapseSideSurvey" + question.id.to_s %>">
                               <%= question.question %>
                        </a>
                    </td>
                    <td>                                                
                        <span class="arrow-down"></span>
                    </td>
                </tr>
            </table>                 
        </div>
        <div id="<%= "collapseSideSurvey" + question.id.to_s %>" class="panel-collapse collapse in">
             <div class="panel-body ">
                <% Answer.where(question_id: question.id).each do |answer| %>
                <%
                label_class = "btn-block btn btn-default label-choice"
                check_box_checked = false
                unless @answer_ids.nil?
                if @answer_ids.include? b.value
                label_class = "btn-block btn btn-default active-label label-choice-active"
                check_box_checked = true
                end
                end
                %>
                <div class="row" style="margin-bottom: 10px;">
                    <div class="col-xs-10">
                        <div class="row">
                            <div class="btn-group btn-group-justified" data-toggle="buttons">
                                <label class="<%= label_class %>" for="question_<%= question.id %>_<%= answer.id %>" data-value="<%= answer.id %>">
                                    <input id="question_<%= question.id %>_<%= answer.id %>" type="checkbox" value="<%= answer.id %>" name="question[<%= question.id %>][]" <%= if check_box_checked then "checked=\"checked\"" else "" end %>>
                                           <%= answer.answer %>
                                           </input>

                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-2">
                        <div class="row">
                            <button class="btn btn-lg btn-link btn-block answer-details-btn-inactive"><strong>?</strong></button>
                            <div class="answer-details-box pull-right" style="">
                                <%= answer.desc %>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>
<%= submit_tag 'Search', class: "btn btn-green btn-success btn-lg btn-block" , id: "close-survey"%>
<% end %>
</div>

app/views/programs/admin_submit.html.erb
<%= render 'form' %>

app/views/programs/edit.html.erb
<h1>Editing program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<%= render 'search' %>

<div style="background-color: #222222;top:51px;padding: 5px 25px;width: 100%;position: fixed;font-family: 'Open Sans', sans-serif;font-size: 1em; color: white;z-index: 100;">    
    Programs available to leaders, entrepreneurs and business owners.
</div>


<div class="container-fluid" style="margin-top: 75px;">
    <div class="row">
        <div class="col-md-12">
            <table class="table" style="height: 100%">
                <tr style="background-color: transparent;height: 100%">
                    <td width="550" class="survey" style="height: 100%;">
                        <div class="col-md-12" style="height: 100%;background-color: #44BBFF; border: 0px solid red;padding: 10px">
                            <%= form_tag '/search', :method => :get, remote: true do %>
                            <div class="panel-group" id="accordion">
                                <% Question.all.order(:id).each do |question| %>
                                <div class="panel panel-default">
                                    <div class="panel-heading survey-box" target="<%= "collapse" + question.id.to_s %>">
                                         <table style="width: 100%">
                                            <tr>
                                                <td >  
                                                    <a data-toggle="collapse" data-parent="#accordion" href="<%= "#collapse" + question.id.to_s %>">
                                                       <%= question.question %>
                                                </a>
                                            </td>
                                            <td>                                                
                                                <span class="arrow-down"></span>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div id="<%= "collapse" + question.id.to_s %>" class="panel-collapse collapse">
                                     <div class="panel-body ">
                                        <% Answer.where(question_id: question.id).each do |answer| %>
                                        <%
                                        label_class = "btn-block btn btn-lg btn-default label-choice"
                                        check_box_checked = false
                                        unless @answer_ids.nil?
                                        if @answer_ids.include? answer.id
                                        label_class = "btn-block btn btn-lg btn-default active-label label-choice-active"
                                        check_box_checked = true
                                        end
                                        end
                                        %>
                                        <div class="row" style="margin-bottom: 10px;">
                                            <div class="col-xs-11">
                                                <div class="row">
                                                    <div class="btn-group btn-group-justified" data-toggle="buttons">
                                                        <label class="<%= label_class %>" for="question_<%= question.id %>_<%= answer.id %>" data-value="<%= answer.id %>">
                                                            <input id="question_<%= question.id %>_<%= answer.id %>" type="checkbox" value="<%= answer.id %>" name="question[<%= question.id %>][]" <%= if check_box_checked then "checked=\"checked\"" else "" end %>>
                                                                   <%= answer.answer %>
                                                                   </input>

                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-xs-1">
                                                <div class="row">
                                                    <button class="btn btn-lg btn-link btn-block answer-details-btn-inactive"><strong>?</strong></button>
                                                    <div class="answer-details-box pull-right" style="">
                                                        <%= answer.desc %>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <% end %>
                                        <input type="hidden" name="question[<%= question.id %>][]"></input>
                                    </div>
                                </div>
                            </div>
                            <% end %>
                        </div>
                        <div class="form-group">
                            <%= submit_tag 'Search', id: "main-survey", class: "btn btn-block btn-green btn-success btn-lg" %>
                        </div>
                        <% end %>
                    </div>
                </td>
                <td>
                    <div class="answer">
                        <div class="panel-group" id="accordion2">
                            <div id='results'>
                                <%= render 'results' %>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>
<br/>
</div>

app/views/programs/new.html.erb
<%= render 'form' %>

app/views/programs/results.js.erb
$("label").has("input:checked").removeClass("label-choice").addClass("active-label label-choice-active active")
$('#results').html("<%= j render partial: 'results', locals: { programs: @programs } %>");

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @program.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @program.desc %>
</p>

<p>
  <strong>Website:</strong>
  <%= @program.website %>
</p>

<ul>
  <% Question.all.each do |question| %>
    <li>
      <%= question.question %>
      <ul>
        <% question.answers.each do |answer| %>
          <li>
          <%= content_tag(:div, class: ('selected' if @program.answers.include? answer)) do %>
              <%= answer.answer %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/programs/submit.html.erb
<%= render 'form' %>