config/routes.rb
CousinsWebsite::Application.routes.draw do

  root 'programs#index'

  get '/search' => 'programs#search'
  post '/search' => 'programs#search'

  get '/submit' => 'programs#submit'
  get '/admin_submit' => 'programs#admin_submit'

  get '/admin' => 'pages#admin'

  resources :programs

  post '/programs/:id/toggle_published' => 'programs#toggle_published', defaults: { format: :json }

  resources :answers

  resources :questions

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :program_answers
  has_many :programs, :through => :program_answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
    render layout: 'admin'
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    render layout: 'admin'
  end

  # GET /answers/new
  def new
    @answer = Answer.new
    render layout: 'admin'
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to '/questions', notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to '/questions', notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to '/questions' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:answer, :desc, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :desc, placeholder: 'Description' %><br>
    <%= f.label :answer %><br>
    <%= f.text_area :answer %><br>
  </div>
  <%= f.hidden_field :question_id, :value => params['question_id'].to_i %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

app/views/answers/index.html.erb
<div class="container-fluid" style="margin-top: 50px;">
  <table>
    <thead>
      <tr>
        <th>Answer</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @answers.each do |answer| %>
        <tr>
          <td><%= answer.answer %></td>
          <td><%= link_to 'Show', answer %></td>
          <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
          <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Answer', new_answer_path %>
</div>

app/views/answers/new.html.erb
<div class="container-fluid" style="margin-top: 50px;">
  <%= render 'form' %>

  <%= link_to 'Back', questions_path %>
</div>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Answer:</strong>
  <%= @answer.answer %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>